apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config-secret
spec:
  replicas: 1                              # pod 수 지정
  selector:
    matchLabels:
      app: nginx                           # 라벨이app : nginx인 pod를 관리
  template:
    metadata:
      labels:
        app: nginx                          # pod에 붙일 라벨
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.20
          envFrom:
            - configMapRef:
                name: configmap-conn         # ConfigMap 연결
            - secretRef:
                name: secret-password        # Secret 연결