apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: nginx-volume
    image: nginx
    volumeMounts:               # 사용할 볼륨 마운트
    - name: storage
      mountPath: /mnt/data      # 컨테이너에서 접근할 볼륨 위
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: volume-pvc      # 참조할 PVC